---

- name: yum install yum-utils
  yum: pkg=yum-utils state=latest
- name: yum install ius
  yum: pkg=https://centos7.iuscommunity.org/ius-release.rpm
- name: yum install python lastest
  yum: pkg=python36u
- name: yum install pip3
  yum:
    name: python36u-pip
- name: symbolic link pip3
  file:
    src: /usr/bin/pip3.6
    dest: /usr/bin/pip3
    state: link
- name: yum install python3-devel
  yum:
    name: python36u-devel
- name: ensure ntpd is at the latest version
  yum: pkg=ntp state=latest
  notify:
  - restart ntpd

- name: create python3 symbolic link
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link
- name: pip install tensorflow
  pip:
    name: tensorflow
    executable: pip3
- name: pip install scipy
  pip:
    name: scipy
    executable: pip3
- name: pip install jupyter
  pip:
    name: jupyter
    executable: pip3
- name: locate jupyter conf
  template: src=jupyter_notebook_config.py dest=/home/vagrant/.jupyter/jupyter_notebook_config.py
- name: locate jupyter shell
  copy:
    src: jupyter.sh
    dest: /usr/bin/jupyter.sh
    mode: 0755
  #- name: launch jupyter notebook
  #  shell: /usr/bin/jupyter.sh &

